training_data_paths:
- "/home/mali2/chronos-forecasting/ptb_arrow/client01.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client02.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client03.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client04.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client05.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client06.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client07.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client08.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client09.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client010.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client011.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client012.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client013.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client014.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client015.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client016.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client017.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client018.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client019.arrow"
- "/home/mali2/chronos-forecasting/ptb_arrow/client020.arrow"
probability:
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
- 0.05
context_length: 512
prediction_length: 64
min_past: 60
max_steps: 200_000
save_steps: 100_000
log_steps: 500
per_device_train_batch_size: 32
learning_rate: 0.001
optim: adamw_torch_fused
num_samples: 20
shuffle_buffer_length: 100_000
gradient_accumulation_steps: 1
model_id: google/t5-efficient-tiny
model_type: seq2seq
random_init: true
tie_embeddings: true
output_dir: ./output/
tf32: true
torch_compile: true
tokenizer_class: "MeanScaleUniformBins"
tokenizer_kwargs:
  low_limit: -15.0
  high_limit: 15.0
n_tokens: 4096
lr_scheduler_type: linear
warmup_ratio: 0.0
dataloader_num_workers: 1
max_missing_prop: 0.9
use_eos_token: true
